"""
Django settings for BookShop project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv


# مسیر اصلی پروژه برای استفاده در تنظیمات مسیرها
BASE_DIR = Path(__file__).resolve().parent.parent

# کلید امنیتی پروژه - در حالت production باید در .env باشد
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = 'django-insecure-(10$-tp52rzgvq$a%g@5b0_o4287**&)0b-n@r940dvltcwer-'

# فعال‌سازی حالت debug فقط در توسعه - در production باید False باشد
DEBUG = True

# لیست دامنه‌های مجاز برای دسترسی به پروژه
ALLOWED_HOSTS = ['mokabookshop.pythonanywhere.com', '127.0.0.1', 'localhost']

# اپلیکیشن‌های نصب‌شده در پروژه

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'shop',  # اپلیکیشن اصلی فروشگاه کتاب
    'adminsortable2',   # برای مرتب‌سازی اعضای تیم در پنل مدیریت
    'import_export',    # برای ایمپورت و اکسپورت داده‌ها در پنل مدیریت

]

# مدل کاربر سفارشی برای افزودن فیلدهای اضافی
AUTH_USER_MODEL = 'shop.CustomUser'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BookShop.urls'

# مسیر قالب‌ها و پردازشگرهای زمینه
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],   # مسیر قالب‌های HTML
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.cart_item_count',    # شمارش آیتم‌های سبد خرید در نوار ناوبری
            ],
        },
    },
]

WSGI_APPLICATION = 'BookShop.wsgi.application'


# تنظیمات پایگاه داده SQLite برای توسعه
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# اعتبارسنجی رمز عبور برای امنیت بیشتر کاربران
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
        'min_length': 8,
    }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# تنظیمات زبان و منطقه زمانی برای فارسی‌سازی کامل پروژه
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fa'      
TIME_ZONE = 'Asia/Tehran'  
USE_I18N = True            
USE_TZ = True             

# مسیرهای فایل‌های استاتیک و رسانه‌ای
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [ BASE_DIR / 'static' ]   # مسیر فایل‌های CSS و JS
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'   # مسیر ذخیره تصاویر آپلود شده

# مسیر پیش‌فرض برای صفحه ورود
LOGIN_URL = '/login/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# بارگذاری متغیرهای محیطی از فایل .env برای امنیت اطلاعات حساس
load_dotenv(dotenv_path=os.path.join(BASE_DIR, '.env'))

# تنظیمات ایمیل برای ارسال پیام‌های بازیابی رمز و تماس با ما
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')  # ایمیل ارسال‌کننده برای بازیابی رمز
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('EMAIL_HOST_USER')

CONTACT_EMAIL_USER = os.environ.get('CONTACT_EMAIL_USER')  # ایمیل دریافت‌کننده فرم تماس با ما
CONTACT_EMAIL_PASSWORD = os.environ.get('CONTACT_EMAIL_PASSWORD')

# شناسه تستی زرین‌پال برای پرداخت آنلاین در حالت sandbox

ZARINPAL_MERCHANT_ID = 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX'  # مقدار تستی

# تنظیمات session برای مدت اعتبار و بسته نشدن با بستن مرورگر

SESSION_COOKIE_AGE = 3600  # اعتبار یک‌ساعته
SESSION_EXPIRE_AT_BROWSER_CLOSE = False




