# Generated by Django 5.2.4 on 2025-08-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_book_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('role', models.CharField(max_length=100, verbose_name='نقش')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team_photos/', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'عضو تیم',
                'verbose_name_plural': 'اعضای تیم',
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('novel', 'رمان'), ('science', 'علمی'), ('kids', 'کودک'), ('history', 'تاریخی'), ('general', 'عمومی')], db_index=True, default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
