# Generated by Django 5.2.4 on 2025-09-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_teammember_options_remove_teammember_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
    ]
