# Generated by Django 5.2.4 on 2025-09-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_rename_description_book_introduction_book_translator'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('general', 'عمومی'), ('science', 'علمی'), ('novel', 'رمان'), ('history', 'تاریخی'), ('child_ya', 'کودک و نوجوان')], db_index=True, default='general', max_length=50),
        ),
    ]
