# Generated by Django 5.2.4 on 2025-09-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_order_total_price_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='نمایش در بخش جدیدترین'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='نمایش در بخش محبوب\u200cترین'),
        ),
    ]
