# Generated by Django 5.2.6 on 2025-09-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_order_user_order_number_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'پرداخت شده'), ('pending', 'در انتظار پرداخت'), ('canceled', 'لغو شده'), ('failed', 'پرداخت ناموفق'), ('expired', 'مهلت پرداخت تمام شده'), ('error', 'خطای سیستمی'), ('test_paid', 'پرداخت آزمایشی')], default='pending', max_length=20),
        ),
    ]
