# Generated by Django 5.2.6 on 2025-09-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_order_number',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'پرداخت شده')], default='paid', max_length=20),
        ),
    ]
