# Generated by Django 5.2.4 on 2025-09-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_order_user_order_number_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'کتاب', 'verbose_name_plural': 'کتاب\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'پیام', 'verbose_name_plural': 'پیام\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'نقد', 'verbose_name_plural': 'نقدها'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'عضو تیم', 'verbose_name_plural': 'اعضای تیم'},
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'verbose_name': 'علاقه\u200cمندی', 'verbose_name_plural': 'علاقه\u200cمندی\u200cها'},
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together=set(),
        ),
    ]
